#!/usr/bin/bash

code="`cat ./js/$1.js`"

echo "
IN=\``cat ./input.txt`\`;
let hrstart = process.hrtime();
$code;
console.log('Answer: '+OUT);
console.log('Took '+process.hrtime(hrstart)[1]/1000000+'ms');
" | node

echo "Stats: `echo "$code" | wc -l` lines, `echo $code | wc -c` characters"